{
	"resultsPerPage": 20,
	"startIndex": 0,
	"totalResults": 4,
	"result": {
		"CVE_data_type": "CVE",
		"CVE_data_format": "MITRE",
		"CVE_data_version": "4.0",
		"CVE_data_timestamp": "2020-09-18T03:37Z",
		"CVE_Items": [
			{
				"cve": {
					"data_type": "CVE",
					"data_format": "MITRE",
					"data_version": "4.0",
					"CVE_data_meta": {
						"ID": "CVE-2017-12852",
						"ASSIGNER": "cve@mitre.org"
					},
					"problemtype": {
						"problemtype_data": [
							{
								"description": [
									{
										"lang": "en",
										"value": "CWE-835"
									}
								]
							}
						]
					},
					"references": {
						"reference_data": [
							{
								"url": "https://github.com/numpy/numpy/issues/9560#issuecomment-322395292",
								"name": "https://github.com/numpy/numpy/issues/9560#issuecomment-322395292",
								"refsource": "CONFIRM",
								"tags": [
									"Exploit",
									"Third Party Advisory"
								]
							},
							{
								"url": "https://github.com/BT123/testcasesForMyRequest/tree/master/CVE-2017-12852",
								"name": "https://github.com/BT123/testcasesForMyRequest/tree/master/CVE-2017-12852",
								"refsource": "MISC"
							}
						]
					},
					"description": {
						"description_data": [
							{
								"lang": "en",
								"value": "The numpy.pad function in Numpy 1.13.1 and older versions is missing input validation. An empty list or ndarray will stick into an infinite loop, which can allow attackers to cause a DoS attack."
							}
						]
					}
				},
				"configurations": {
					"CVE_data_version": "4.0",
					"nodes": [
						{
							"operator": "OR",
							"cpe_match": [
								{
									"vulnerable": true,
									"cpe23Uri": "cpe:2.3:a:numpy:numpy:*:*:*:*:*:*:*:*",
									"versionEndIncluding": "1.13.1"
								}
							]
						}
					]
				},
				"impact": {
					"baseMetricV3": {
						"cvssV3": {
							"version": "3.0",
							"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
							"attackVector": "NETWORK",
							"attackComplexity": "LOW",
							"privilegesRequired": "NONE",
							"userInteraction": "NONE",
							"scope": "UNCHANGED",
							"confidentialityImpact": "NONE",
							"integrityImpact": "NONE",
							"availabilityImpact": "HIGH",
							"baseScore": 7.5,
							"baseSeverity": "HIGH"
						},
						"exploitabilityScore": 3.9,
						"impactScore": 3.6
					},
					"baseMetricV2": {
						"cvssV2": {
							"version": "2.0",
							"vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
							"accessVector": "NETWORK",
							"accessComplexity": "LOW",
							"authentication": "NONE",
							"confidentialityImpact": "NONE",
							"integrityImpact": "NONE",
							"availabilityImpact": "PARTIAL",
							"baseScore": 5.0
						},
						"severity": "MEDIUM",
						"exploitabilityScore": 10.0,
						"impactScore": 2.9,
						"acInsufInfo": true,
						"obtainAllPrivilege": false,
						"obtainUserPrivilege": false,
						"obtainOtherPrivilege": false,
						"userInteractionRequired": false
					}
				},
				"publishedDate": "2017-08-15T16:29Z",
				"lastModifiedDate": "2019-10-03T00:03Z"
			},
			{
				"cve": {
					"data_type": "CVE",
					"data_format": "MITRE",
					"data_version": "4.0",
					"CVE_data_meta": {
						"ID": "CVE-2019-6446",
						"ASSIGNER": "cve@mitre.org"
					},
					"problemtype": {
						"problemtype_data": [
							{
								"description": [
									{
										"lang": "en",
										"value": "CWE-502"
									}
								]
							}
						]
					},
					"references": {
						"reference_data": [
							{
								"url": "https://github.com/numpy/numpy/issues/12759",
								"name": "https://github.com/numpy/numpy/issues/12759",
								"refsource": "MISC",
								"tags": [
									"Exploit",
									"Issue Tracking",
									"Third Party Advisory"
								]
							},
							{
								"url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208",
								"name": "https://bugzilla.suse.com/show_bug.cgi?id=1122208",
								"refsource": "MISC",
								"tags": [
									"Exploit",
									"Issue Tracking",
									"Third Party Advisory"
								]
							},
							{
								"url": "http://www.securityfocus.com/bid/106670",
								"name": "106670",
								"refsource": "BID",
								"tags": [
									"Third Party Advisory",
									"VDB Entry"
								]
							},
							{
								"url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/",
								"name": "FEDORA-2019-1dfe95a864",
								"refsource": "FEDORA",
								"tags": [
									"Third Party Advisory"
								]
							},
							{
								"url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html",
								"name": "openSUSE-SU-2019:2227",
								"refsource": "SUSE"
							},
							{
								"url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html",
								"name": "openSUSE-SU-2019:2225",
								"refsource": "SUSE"
							},
							{
								"url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html",
								"name": "openSUSE-SU-2019:2259",
								"refsource": "SUSE"
							},
							{
								"url": "https://access.redhat.com/errata/RHSA-2019:3335",
								"name": "RHSA-2019:3335",
								"refsource": "REDHAT"
							},
							{
								"url": "https://access.redhat.com/errata/RHSA-2019:3704",
								"name": "RHSA-2019:3704",
								"refsource": "REDHAT"
							}
						]
					},
					"description": {
						"description_data": [
							{
								"lang": "en",
								"value": "** DISPUTED **   An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources."
							}
						]
					}
				},
				"configurations": {
					"CVE_data_version": "4.0",
					"nodes": [
						{
							"operator": "OR",
							"cpe_match": [
								{
									"vulnerable": true,
									"cpe23Uri": "cpe:2.3:a:numpy:numpy:*:*:*:*:*:*:*:*",
									"versionEndIncluding": "1.16.0"
								}
							]
						},
						{
							"operator": "OR",
							"cpe_match": [
								{
									"vulnerable": true,
									"cpe23Uri": "cpe:2.3:o:fedoraproject:fedora:30:*:*:*:*:*:*:*"
								}
							]
						}
					]
				},
				"impact": {
					"baseMetricV3": {
						"cvssV3": {
							"version": "3.0",
							"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
							"attackVector": "NETWORK",
							"attackComplexity": "LOW",
							"privilegesRequired": "NONE",
							"userInteraction": "NONE",
							"scope": "UNCHANGED",
							"confidentialityImpact": "HIGH",
							"integrityImpact": "HIGH",
							"availabilityImpact": "HIGH",
							"baseScore": 9.8,
							"baseSeverity": "CRITICAL"
						},
						"exploitabilityScore": 3.9,
						"impactScore": 5.9
					},
					"baseMetricV2": {
						"cvssV2": {
							"version": "2.0",
							"vectorString": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
							"accessVector": "NETWORK",
							"accessComplexity": "LOW",
							"authentication": "NONE",
							"confidentialityImpact": "PARTIAL",
							"integrityImpact": "PARTIAL",
							"availabilityImpact": "PARTIAL",
							"baseScore": 7.5
						},
						"severity": "HIGH",
						"exploitabilityScore": 10.0,
						"impactScore": 6.4,
						"acInsufInfo": false,
						"obtainAllPrivilege": false,
						"obtainUserPrivilege": false,
						"obtainOtherPrivilege": false,
						"userInteractionRequired": false
					}
				},
				"publishedDate": "2019-01-16T05:29Z",
				"lastModifiedDate": "2019-10-01T00:15Z"
			},
			{
				"cve": {
					"data_type": "CVE",
					"data_format": "MITRE",
					"data_version": "4.0",
					"CVE_data_meta": {
						"ID": "CVE-2014-1859",
						"ASSIGNER": "cve@mitre.org"
					},
					"problemtype": {
						"problemtype_data": [
							{
								"description": [
									{
										"lang": "en",
										"value": "CWE-59"
									}
								]
							}
						]
					},
					"references": {
						"reference_data": [
							{
								"url": "https://github.com/numpy/numpy/pull/4262",
								"name": "https://github.com/numpy/numpy/pull/4262",
								"refsource": "CONFIRM",
								"tags": [
									"Issue Tracking",
									"Patch",
									"Third Party Advisory"
								]
							},
							{
								"url": "https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15",
								"name": "https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15",
								"refsource": "CONFIRM",
								"tags": [
									"Patch",
									"Third Party Advisory"
								]
							},
							{
								"url": "https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst",
								"name": "https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst",
								"refsource": "CONFIRM",
								"tags": [
									"Patch",
									"Third Party Advisory"
								]
							},
							{
								"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/91317",
								"name": "numpy-cve20141859-symlink(91317)",
								"refsource": "XF",
								"tags": [
									"Issue Tracking",
									"Third Party Advisory",
									"VDB Entry"
								]
							},
							{
								"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1062009",
								"name": "https://bugzilla.redhat.com/show_bug.cgi?id=1062009",
								"refsource": "CONFIRM",
								"tags": [
									"Issue Tracking",
									"Patch"
								]
							},
							{
								"url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778",
								"name": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778",
								"refsource": "CONFIRM",
								"tags": [
									"Issue Tracking",
									"Patch",
									"Third Party Advisory"
								]
							},
							{
								"url": "http://www.securityfocus.com/bid/65440",
								"name": "65440",
								"refsource": "BID",
								"tags": [
									"Third Party Advisory",
									"VDB Entry"
								]
							},
							{
								"url": "http://www.openwall.com/lists/oss-security/2014/02/08/3",
								"name": "[oss-security] 20140207 Re: CVE request: f2py insecure temporary file use",
								"refsource": "MLIST",
								"tags": [
									"Issue Tracking",
									"Mailing List",
									"Patch",
									"Third Party Advisory"
								]
							},
							{
								"url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128781.html",
								"name": "FEDORA-2014-2387",
								"refsource": "FEDORA",
								"tags": [
									"Issue Tracking",
									"Third Party Advisory"
								]
							},
							{
								"url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128358.html",
								"name": "FEDORA-2014-2289",
								"refsource": "FEDORA",
								"tags": [
									"Issue Tracking",
									"Third Party Advisory"
								]
							}
						]
					},
					"description": {
						"description_data": [
							{
								"lang": "en",
								"value": "(1) core/tests/test_memmap.py, (2) core/tests/test_multiarray.py, (3) f2py/f2py2e.py, and (4) lib/tests/test_io.py in NumPy before 1.8.1 allow local users to write to arbitrary files via a symlink attack on a temporary file."
							}
						]
					}
				},
				"configurations": {
					"CVE_data_version": "4.0",
					"nodes": [
						{
							"operator": "OR",
							"cpe_match": [
								{
									"vulnerable": true,
									"cpe23Uri": "cpe:2.3:a:numpy:numpy:*:*:*:*:*:*:*:*",
									"versionEndIncluding": "1.8.0"
								},
								{
									"vulnerable": true,
									"cpe23Uri": "cpe:2.3:a:numpy:numpy:1.8.1:rc1:*:*:*:*:*:*"
								}
							]
						},
						{
							"operator": "OR",
							"cpe_match": [
								{
									"vulnerable": true,
									"cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux:7.0:*:*:*:*:*:*:*"
								},
								{
									"vulnerable": true,
									"cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux:6.0:*:*:*:*:*:*:*"
								},
								{
									"vulnerable": true,
									"cpe23Uri": "cpe:2.3:o:fedoraproject:fedora:19:*:*:*:*:*:*:*"
								},
								{
									"vulnerable": true,
									"cpe23Uri": "cpe:2.3:o:fedoraproject:fedora:20:*:*:*:*:*:*:*"
								}
							]
						}
					]
				},
				"impact": {
					"baseMetricV3": {
						"cvssV3": {
							"version": "3.0",
							"vectorString": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
							"attackVector": "LOCAL",
							"attackComplexity": "LOW",
							"privilegesRequired": "LOW",
							"userInteraction": "NONE",
							"scope": "UNCHANGED",
							"confidentialityImpact": "NONE",
							"integrityImpact": "HIGH",
							"availabilityImpact": "NONE",
							"baseScore": 5.5,
							"baseSeverity": "MEDIUM"
						},
						"exploitabilityScore": 1.8,
						"impactScore": 3.6
					},
					"baseMetricV2": {
						"cvssV2": {
							"version": "2.0",
							"vectorString": "AV:L/AC:L/Au:N/C:N/I:P/A:N",
							"accessVector": "LOCAL",
							"accessComplexity": "LOW",
							"authentication": "NONE",
							"confidentialityImpact": "NONE",
							"integrityImpact": "PARTIAL",
							"availabilityImpact": "NONE",
							"baseScore": 2.1
						},
						"severity": "LOW",
						"exploitabilityScore": 3.9,
						"impactScore": 2.9,
						"obtainAllPrivilege": false,
						"obtainUserPrivilege": false,
						"obtainOtherPrivilege": false,
						"userInteractionRequired": false
					}
				},
				"publishedDate": "2018-01-08T19:29Z",
				"lastModifiedDate": "2019-04-22T17:48Z"
			},
			{
				"cve": {
					"data_type": "CVE",
					"data_format": "MITRE",
					"data_version": "4.0",
					"CVE_data_meta": {
						"ID": "CVE-2014-1858",
						"ASSIGNER": "cve@mitre.org"
					},
					"problemtype": {
						"problemtype_data": [
							{
								"description": [
									{
										"lang": "en",
										"value": "CWE-20"
									}
								]
							}
						]
					},
					"references": {
						"reference_data": [
							{
								"url": "https://github.com/numpy/numpy/pull/4262",
								"name": "https://github.com/numpy/numpy/pull/4262",
								"refsource": "CONFIRM",
								"tags": [
									"Third Party Advisory"
								]
							},
							{
								"url": "https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15",
								"name": "https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15",
								"refsource": "CONFIRM",
								"tags": [
									"Third Party Advisory"
								]
							},
							{
								"url": "https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst",
								"name": "https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst",
								"refsource": "CONFIRM",
								"tags": [
									"Third Party Advisory"
								]
							},
							{
								"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/91318",
								"name": "numpy-cve20141858-symlink(91318)",
								"refsource": "XF",
								"tags": [
									"Third Party Advisory",
									"VDB Entry"
								]
							},
							{
								"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1062009",
								"name": "https://bugzilla.redhat.com/show_bug.cgi?id=1062009",
								"refsource": "CONFIRM",
								"tags": [
									"Issue Tracking",
									"Third Party Advisory"
								]
							},
							{
								"url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778",
								"name": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778",
								"refsource": "CONFIRM",
								"tags": [
									"Mailing List",
									"Third Party Advisory"
								]
							},
							{
								"url": "http://www.securityfocus.com/bid/65441",
								"name": "65441",
								"refsource": "BID",
								"tags": [
									"Third Party Advisory",
									"VDB Entry"
								]
							},
							{
								"url": "http://www.openwall.com/lists/oss-security/2014/02/08/3",
								"name": "[oss-security] 20140207 Re: CVE request: f2py insecure temporary file use",
								"refsource": "MLIST",
								"tags": [
									"Mailing List",
									"Third Party Advisory"
								]
							},
							{
								"url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128781.html",
								"name": "FEDORA-2014-2387",
								"refsource": "FEDORA",
								"tags": [
									"Third Party Advisory"
								]
							},
							{
								"url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128358.html",
								"name": "FEDORA-2014-2289",
								"refsource": "FEDORA",
								"tags": [
									"Third Party Advisory"
								]
							}
						]
					},
					"description": {
						"description_data": [
							{
								"lang": "en",
								"value": "__init__.py in f2py in NumPy before 1.8.1 allows local users to write to arbitrary files via a symlink attack on a temporary file."
							}
						]
					}
				},
				"configurations": {
					"CVE_data_version": "4.0",
					"nodes": [
						{
							"operator": "OR",
							"cpe_match": [
								{
									"vulnerable": true,
									"cpe23Uri": "cpe:2.3:a:numpy:numpy:*:*:*:*:*:*:*:*",
									"versionEndExcluding": "1.8.1"
								}
							]
						}
					]
				},
				"impact": {
					"baseMetricV3": {
						"cvssV3": {
							"version": "3.0",
							"vectorString": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
							"attackVector": "LOCAL",
							"attackComplexity": "LOW",
							"privilegesRequired": "LOW",
							"userInteraction": "NONE",
							"scope": "UNCHANGED",
							"confidentialityImpact": "NONE",
							"integrityImpact": "HIGH",
							"availabilityImpact": "NONE",
							"baseScore": 5.5,
							"baseSeverity": "MEDIUM"
						},
						"exploitabilityScore": 1.8,
						"impactScore": 3.6
					},
					"baseMetricV2": {
						"cvssV2": {
							"version": "2.0",
							"vectorString": "AV:L/AC:L/Au:N/C:N/I:P/A:N",
							"accessVector": "LOCAL",
							"accessComplexity": "LOW",
							"authentication": "NONE",
							"confidentialityImpact": "NONE",
							"integrityImpact": "PARTIAL",
							"availabilityImpact": "NONE",
							"baseScore": 2.1
						},
						"severity": "LOW",
						"exploitabilityScore": 3.9,
						"impactScore": 2.9,
						"obtainAllPrivilege": false,
						"obtainUserPrivilege": false,
						"obtainOtherPrivilege": false,
						"userInteractionRequired": false
					}
				},
				"publishedDate": "2018-01-08T19:29Z",
				"lastModifiedDate": "2018-01-30T14:44Z"
			}
		]
	}
}